version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: korkomunisa-app
    container_name: korkomunisa_app
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - app_storage:/var/www/html/storage
      - app_database:/var/www/html/database
      - letsencrypt:/etc/letsencrypt
      - ./.env:/var/www/html/.env
    deploy:
      resources:
        limits:
          memory: 4G

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    image: korkomunisa-app
    container_name: korkomunisa_queue
    restart: unless-stopped
    entrypoint: ["php", "artisan", "queue:work", "--sleep=3", "--tries=3", "--max-time=3600"]
    volumes:
      - app_storage:/var/www/html/storage
      - app_database:/var/www/html/database
      - ./.env:/var/www/html/.env

volumes:
  app_storage:
  app_database:
  letsencrypt:
